/*
 * Copyright (c) 2014. This code is a LogosProg property. All Rights Reserved.
 */

import display.TerminalData;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Created by forando on 26.08.14.
 * Struct object just used for communcation -- sent on the object stream.<br>
 * The contained int and Date objects are both Serializable, otherwise
 * the serialization would fail.
 */
public class SocketMessage implements Serializable {
    public final static int REGISTER_SOCKET = 30;
    public final static int CLOSE_SOCKET = 31;
    public final static int HOLD_CLIENT = 32;
    public final static int RELEASE_CLIENT = 33;

    //The types of clients:
    public static final int PRINTER = 0;
    public static final int TERMINAL = 1;
    public static final int DISPLAY = 2;


    public int id;
    /**
     * A command type to be committed.<br>
     */
    public int operation;
    public boolean received;
    /**
     * Means has this object been generated by client and than transferred through socket,
     * or it's been generated locally on the server side on a basis of ByteArray that was
     * received from a client.
     */
    public boolean transferable;
    public Date date;

    /**
     *
     * @param id The id index
     * @param operation The command to be executed
     * @param date Current time stamp
     * @param transferable See {@link #transferable}
     */
    public SocketMessage(int id, int operation, Date date, boolean transferable) {
        this.id = id;
        this.operation = operation;
        this.received = false;
        this.date = date;
        this.transferable = transferable;
    }
}
